#!/usr/bin/env runhaskell

import Development.Shake

main = shake $ do
    want ["index.html"]
    "*.html" *> \html -> do
        let md = html `replaceExtension` "md"
        need [md]
        system $ [ "pandoc"
                 , "-f", "markdown"
                 , "-t", "s5"
                 , "--smart"
                 , "-o", html
                 md
                 ]

-- vim: set filetype=haskell:
