#!/usr/bin/env runhaskell

{-# LANGUAGE OverloadedStrings #-}

import Development.Shake
import Development.Shake.FilePath
import Prelude hiding (FilePath)
import Shelly
import System.Environment

main = do
    args <- getArgs
    case args of
        ("help":_)  -> do
            putStrLn "Help M-e-e-e!"
        ("clean":_) -> do
            shelly $ verbosely $ rm_f "index.html"
        _ -> rules

rules = shake shakeOptions $ do

    want ["index.html"]
    "*.html" *> \html -> do
        let md = html `replaceExtension` "md"
        need [md]
        system' "pandoc" $ [ "-f", "markdown"
                           , "-t", "s5"
                           , "--incremental"
                           , "--smart"
                           , "--standalone"
                           , "-o", html
                           , md
                           ]

-- vim: set filetype=haskell:
